spring.application.name=Spring_Rest_Data_Jpa_Project
server.port=9000
#Configuring DB Connection Properties
#spring.datasource.driver-class-name=com.mysql.ch.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshow1
spring.datasource.username=root
spring.datasource.password=Ycpait24
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
